# Generated by Django 3.1.7 on 2021-02-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeemachine',
            name='model',
            field=models.CharField(choices=[('1', 'base model'), ('2', 'premium model'), ('3', 'deluxe model')], max_length=30),
        ),
        migrations.AlterField(
            model_name='coffeemachine',
            name='product_type',
            field=models.CharField(choices=[('1', 'COFFEE_MACHINE_LARGE'), ('0', 'COFFEE_MACHINE_SMALL'), ('2', 'ESPRESSO_MACHINE')], max_length=30),
        ),
    ]
