# Generated by Django 3.1.7 on 2021-02-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210220_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeemachine',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
