# Generated by Django 3.1.7 on 2021-02-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210220_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeemachine',
            name='water_line_compatible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coffeemachine',
            name='product_type',
            field=models.CharField(choices=[('1', 'LARGE'), ('0', 'SMALL'), ('2', 'ESPRESSO')], max_length=30),
        ),
    ]
