# Generated by Django 3.1.7 on 2021-02-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210220_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('product_type', models.CharField(choices=[('1', 'LARGE'), ('0', 'SMALL'), ('2', 'ESPRESSO')], max_length=30)),
                ('coffee_flavor', models.CharField(choices=[('0', 'vanilla'), ('1', 'caramel'), ('2', 'psl'), ('3', 'mocha'), ('4', 'hazelnut')], max_length=30)),
                ('pack_size', models.CharField(choices=[('1', '1 dozen'), ('3', '3 dozen'), ('5', '5 dozen'), ('7', '7 dozen')], max_length=30)),
            ],
        ),
    ]
